// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH0PfAi0yC-qlIlbqHFi-DKrUEnwJv9RQ',
    appId: '1:777226834682:web:85a1fbfada6ccf15812f43',
    messagingSenderId: '777226834682',
    projectId: 'personalexpensetraker',
    authDomain: 'personalexpensetraker.firebaseapp.com',
    databaseURL: 'https://personalexpensetraker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personalexpensetraker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzcoSDtZbblf51FYOYRC64cI0Li0bM7w',
    appId: '1:777226834682:android:a0d80171249636f0812f43',
    messagingSenderId: '777226834682',
    projectId: 'personalexpensetraker',
    databaseURL: 'https://personalexpensetraker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personalexpensetraker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZSlxA8e9O2fxBOajDIpniAziHZDVN5kA',
    appId: '1:777226834682:ios:fa8161852aec6f36812f43',
    messagingSenderId: '777226834682',
    projectId: 'personalexpensetraker',
    databaseURL: 'https://personalexpensetraker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personalexpensetraker.appspot.com',
    androidClientId: '777226834682-bfu6vsjcrosra9ducgjsu0fj687mnd5q.apps.googleusercontent.com',
    iosClientId: '777226834682-63pfd4grdih5pemmfqceu4e76a0bgkme.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZSlxA8e9O2fxBOajDIpniAziHZDVN5kA',
    appId: '1:777226834682:ios:fa8161852aec6f36812f43',
    messagingSenderId: '777226834682',
    projectId: 'personalexpensetraker',
    databaseURL: 'https://personalexpensetraker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personalexpensetraker.appspot.com',
    androidClientId: '777226834682-bfu6vsjcrosra9ducgjsu0fj687mnd5q.apps.googleusercontent.com',
    iosClientId: '777226834682-63pfd4grdih5pemmfqceu4e76a0bgkme.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH0PfAi0yC-qlIlbqHFi-DKrUEnwJv9RQ',
    appId: '1:777226834682:web:9ec45e29501bfdce812f43',
    messagingSenderId: '777226834682',
    projectId: 'personalexpensetraker',
    authDomain: 'personalexpensetraker.firebaseapp.com',
    databaseURL: 'https://personalexpensetraker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personalexpensetraker.appspot.com',
  );

}